spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
      username: test
      password: test
  application:
    name: product-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka