spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: product-service
  zipkin:
    base-url: http://zipkin:9411
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka:s3cret@discovery-server:8761/eureka