spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service
      authentication-database: admin
      password: test
      username: test
  application:
    name: product-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
#     % of request received that should be sent to zipkin for tracing
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:s3cret@localhost:8761/eureka
server:
  port: 0