eureka:
  instance:
    hostname: localhost
  client:
#    we don't want the server to register itself as a client, since it is a
#    discovery server
    register-with-eureka: false
#    as it is the registry server, we don't need to fetch the registry information
#    it already has access to it locally
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8761

spring:
  application:
    name: discovery-server