eureka:
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:s3cret}
  instance:
    hostname: localhost
  client:
#    we don't want the server to register itself as a client, since it is a
#    discovery server
    register-with-eureka: false
#    as it is the registry server, we don't need to fetch the registry information
#    it already has access to it locally
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#  actuator properties
management:
  # by default all the health endpoints are exposed by actuator -> actuator/health
  endpoints:
    web:
      exposure:
        #       also expose the prometheus actuator endpoint in actuator -> /actuator/prometheus
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8761

spring:
  application:
    name: discovery-server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
#     % of request received that should be sent to zipkin for tracing
      probability: 1.0