server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka:s3cret@discovery-server:8761/eureka
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/spring-boot-microservices-realm
  zipkin:
    base-url: http://zipkin:9411